// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9FOvt8Qx3TknMzmSF5ZWqs-A8VpAHzA',
    appId: '1:886827705692:web:6eed9d65fda2d8a1ae8d99',
    messagingSenderId: '886827705692',
    projectId: 'todo-list-2922a',
    authDomain: 'todo-list-2922a.firebaseapp.com',
    storageBucket: 'todo-list-2922a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvvkkMLKST43vAibjU7DjYSltqwB8gH0',
    appId: '1:886827705692:android:7da145fbc4d9b994ae8d99',
    messagingSenderId: '886827705692',
    projectId: 'todo-list-2922a',
    storageBucket: 'todo-list-2922a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9el9W5KK0CxssTXHNIhtPl8UCZL_m-OY',
    appId: '1:886827705692:ios:690b9fcac05737c5ae8d99',
    messagingSenderId: '886827705692',
    projectId: 'todo-list-2922a',
    storageBucket: 'todo-list-2922a.firebasestorage.app',
    iosBundleId: 'com.domain.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9el9W5KK0CxssTXHNIhtPl8UCZL_m-OY',
    appId: '1:886827705692:ios:690b9fcac05737c5ae8d99',
    messagingSenderId: '886827705692',
    projectId: 'todo-list-2922a',
    storageBucket: 'todo-list-2922a.firebasestorage.app',
    iosBundleId: 'com.domain.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn9FOvt8Qx3TknMzmSF5ZWqs-A8VpAHzA',
    appId: '1:886827705692:web:1a7eb3f585accd97ae8d99',
    messagingSenderId: '886827705692',
    projectId: 'todo-list-2922a',
    authDomain: 'todo-list-2922a.firebaseapp.com',
    storageBucket: 'todo-list-2922a.firebasestorage.app',
  );
}
